### ISSUE TITLE
BrainAmpSeries - Implement downsampling filters

### ISSUE THREAD

**Issue by sappelhoff** [sccn/lsl_archived#264]
Hi everybody,

I am trying to make a real-time application using EEG data streamed from a BrainProducts BrainAmp via the BrainAmpSeries app from the LSL suite.

Is there a way to change the default sampling rate (5kHz) of the amp to something lower? Otherwise, it becomes impossible to use pull_chunk on a time interval of 1second or longer, because the chunk to be pulled will have a very large shape (and thus, the latency will become inaccaptably high around 50ms with my setup).

Currently, my remedy for this problem is using few EEG channels (so that the chunk to be pulled has a smaller shape) and pulling a limited amount of time. But using a lower sampling frequency to begin with would be much nicer and also a big bonus in terms of storing the data on disk.

Thanks,
Stefan

**Comment by cboulay** [comment]
The fastest solution for you would be to modify [this line](https://github.com/sccn/labstreaminglayer/blob/master/Apps/BrainProducts/BrainAmpSeries/mainwindow.cpp#L45) and recompile. 

You're right that this should be something configurable in the GUI, but I don't have access to this hardware so I can't help develop & test this.

**Comment by sappelhoff** [comment]
Thanks for the quick reply - that sounds like a good workaround for now.

Could you perhaps briefly explain how I would recompile the BrainSeriesAmp app? (On Windows or Linux) - or else point me to the resources necessary to learn abot it myself?

**Comment by cboulay** [comment]
The instructions are the same as for most of the other cmake-configurable apps except the argument is `-DLSLAPPS_BrainAmp=ON`. See, for example, [LabRecorder build instructions](https://github.com/sccn/labstreaminglayer/tree/master/Apps/LabRecorder).

**Comment by cboulay** [comment]
Never mind that last post. Those instructions are a bit old. Read [this](https://github.com/sccn/labstreaminglayer/blob/master/INSTALL.md) instead.

**Comment by sappelhoff** [comment]
Thank you @cboulay !

... however, after looking around in the files I am now wondering whether it would be a good idea to simply alter the sampling frequency --> Based on some previous exposure to a similar problem I was looking whether there is some lowpass filtering going on during the acquisition and I [found this](https://github.com/sccn/labstreaminglayer/blob/8d032fb43245be0d8598488d2cf783ac36a97831/Apps/BrainProducts/BrainAmpSeries/BrainAmpIoCtl.h#L169) to perhaps back that up.

Now if I were to change my sampling frequency to 1000Hz and there is also a lowpass filter at 1000Hz, I would run into problems with aliasing :-/

Unfortunately, I am not familiar with whatever programming language the whole app is written in so for now I will have to wait for somebody else to look into this.

**Comment by dmedine** [comment]
The Brain Amp only has 1 sampling rate available on its AD converter and that is 5kHz. The only way to adjust the sampling rate is by downsampling. So altering [this line](https://github.com/sccn/labstreaminglayer/blob/master/Apps/BrainProducts/BrainAmpSeries/mainwindow.cpp#L45) would only lead to all kinds of mischeif. 

The way to improve the app so that it offers a variety of sampling rates is to add downsampling filters like the ones available on the actiCHamp app (you can look at the coefficients [here](https://github.com/sccn/labstreaminglayer/blob/master/Apps/BrainProducts/ActiChamp/mainwindow.cpp#L18-L493) if you like). 

It wouldn't be a huge effort to add this in the future, so I will consider it. At the moment I don't have time to work on these applications, but I intend to do some revisions in a few months when my workload should be a little lighter. August is usually pretty slow.

However, I know that is a long time to wait. One possible option is to run the device through Recorder and stream that through the RDA server. Then, you can pickup a downsampled stream via the LSL RDA client application.

Also, maybe I'm doing DSP in my head wrong, but wouldn't a 1kHz lowpass filter applied to a signal sampled at 1kHz effectively alias down to a 0Hz lowpass filter? That would be very bad indeed!

**Comment by sappelhoff** [comment]
@dmedine thanks for your answer. I was afraid that this is the case, because I couldn't find any information in the BrainProducts manuals as well ...

I actually started out with the RDA client but had a relatively high latency - I am aiming at something around 10ms, but was stuck at 100ms. That's why I switched to the BrainAmpSeries which is supposed to be much faster (also according to [this](http://pressrelease.brainproducts.com/real-time-eeg/) article)

So I am looking forward to your fixes and I'll try to fiddle around with the 5kHz sampling frequency. If I wanted to downsample the online streamed data from 5kHz to 1kHz ... wouldn't I have to lowpass filter every chunk of data before downsampling? What about filter artifacts that I would thus get on each chunk?

**Comment by sappelhoff** [comment]
This issue thread has evolved into something different than what I intended, but I think it is still important to keep it for the purpose of implementing downsampling filters for the BrainAmpSeries app as @dmedine  suggested.

Regarding the remaining latency issue of the BrainAmp, see #269

**Comment by sappelhoff** [comment]
closing this:

- I currently don't need it anymore and interest from others seems to be low
- it's archived.
