### ISSUE TITLE
How to receive the data coming from NIRStar?

### ISSUE THREAD

**Issue by RanjitF** [sccn/lsl_archived#313]
Today I opened the Lab Streaming Layer in the NIRStar software and used LabRecorder to record the data. When I tried to receive the data from NIRStar using 'ReceiveData.m', the code always stuck and could not receive the data. Is there anything special to receive the fNIRS data than receiving the EEG data?

**Comment by cboulay** [comment]
ReceiveData.m is just an example. You will have to modify it to work with your source.
Look at [this line](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Matlab/examples/ReceiveData.m#L9). The resolver is used to find streams, and by default it is parameterized to find any stream with `type` = `EEG`. This probably doesn't work for your NIRStar stream.

Instead of using `'type', 'EEG'`, you can use `'name', <name>` where `<name>` is what you see for the stream in LabRecorder.

[Here](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Matlab/lsl_resolve_byprop.m#L11-L15) is some more info on how you can parameterize `resolve_by_prop` to find your stream.

I suspect this will solve your problem. Please remember to close the issue if it does.
